# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-08 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('scourse', models.CharField(max_length=100)),
                ('cfee', models.IntegerField()),
            ],
        ),
    ]
