# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-08 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('salary', models.BigIntegerField()),
                ('company', models.CharField(max_length=30)),
            ],
        ),
    ]
