# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('salary', models.BigIntegerField()),
            ],
        ),
    ]
