# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-08 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sname', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
